#!/bin/sh

prefix=$1

install="/usr/bin/install -c"
prog='fireflies'
bindir='/usr/lib/xscreensaver'
confdir='/usr/share/xscreensaver/config'
rcfile='/etc/X11/app-defaults/XScreenSaver'

case `uname` in
CYGWIN*|cygwin*|MINGW*|mingw*)
    $install src/$prog $prefix$bindir || exit 1
    echo "Installed $prog in $bindir/"
    ;;
*)
    mkdir -p "$prefix$bindir"
    $install -m 755 src/$prog "$prefix$bindir" || exit 1
    echo "Installed $prog in $prefix$bindir/"
    mkdir -p "$prefix$confdir"
    $install -m 644 fireflies.xml "$prefix$confdir" || exit 1
    echo "Installed fireflies.xml in $prefix$confdir/"
    if [ "$rcfile" != "" ]; then
	sh ./add-xscreensaver "$prefix$rcfile"
	echo "Added 'fireflies' entry to $prefix$rcfile"
    else
	echo "Could not find global XScreensaver file." 
	echo "You can add fireflies to your xscreensaver file by typing:"
	echo "  ./add-xscreensaver <filename>"
	echo "from the build directory.  <filename> would usually look like"
	echo "/home/user/.xscreensaver"
    fi
    ;;
esac
